[package]
name = "zora-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
domain.workspace = true
application.workspace = true
infrastructure.workspace = true
axum.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
ts-rs.workspace = true
garde.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
chrono.workspace = true
tower-http.workspace = true
dotenvy.workspace = true
